// <auto-generated />
using System;
using LocalApi_NoAuthentication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalApi_NoAuthentication.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20210614140856_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LocalApi_NoAuthentication.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Forecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 6, 15, 16, 8, 56, 391, DateTimeKind.Local).AddTicks(1393),
                            Summary = "Scorching",
                            TemperatureC = 28,
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 6, 16, 16, 8, 56, 393, DateTimeKind.Local).AddTicks(211),
                            Summary = "Chilly",
                            TemperatureC = 12,
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 6, 17, 16, 8, 56, 393, DateTimeKind.Local).AddTicks(234),
                            Summary = "Warm",
                            TemperatureC = 21,
                            UserId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
