// <auto-generated />
using System;
using LocalApi_NoAuthentication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalApi_NoAuthentication.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LocalApi_NoAuthentication.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 6, 17, 13, 17, 24, 590, DateTimeKind.Local).AddTicks(638),
                            Summary = "Scorching",
                            TemperatureC = 28,
                            User = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 6, 18, 13, 17, 24, 591, DateTimeKind.Local).AddTicks(9038),
                            Summary = "Chilly",
                            TemperatureC = 12,
                            User = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 6, 19, 13, 17, 24, 591, DateTimeKind.Local).AddTicks(9062),
                            Summary = "Warm",
                            TemperatureC = 21,
                            User = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
